### ISSUE TITLE
an error when running "serif generate"

### ISSUE THREAD

**Issue by luckypoem** [aprescott/serif#60]
hi:
i met the below error.how to fix it ?

```
as3:~/serif-site# serif generate
/usr/local/ruby/lib/ruby/gems/2.0.0/gems/serif-0.5.2/lib/serif/content_file.rb:22:in `initialize': undefined method `join' for nil:NilClass (NoMethodError)
        from /usr/local/ruby/lib/ruby/gems/2.0.0/gems/serif-0.5.2/lib/serif/post.rb:62:in `new'
        from /usr/local/ruby/lib/ruby/gems/2.0.0/gems/serif-0.5.2/lib/serif/post.rb:62:in `block in all'
        from /usr/local/ruby/lib/ruby/gems/2.0.0/gems/serif-0.5.2/lib/serif/post.rb:62:in `map'
        from /usr/local/ruby/lib/ruby/gems/2.0.0/gems/serif-0.5.2/lib/serif/post.rb:62:in `all'
        from /usr/local/ruby/lib/ruby/gems/2.0.0/gems/serif-0.5.2/lib/serif/site.rb:107:in `posts'
        from /usr/local/ruby/lib/ruby/gems/2.0.0/gems/serif-0.5.2/lib/serif/site.rb:281:in `conflicts'
        from /usr/local/ruby/lib/ruby/gems/2.0.0/gems/serif-0.5.2/lib/serif/site.rb:315:in `generate'
        from /usr/local/ruby/lib/ruby/gems/2.0.0/gems/serif-0.5.2/lib/serif/commands.rb:51:in `generate_site'
        from /usr/local/ruby/lib/ruby/gems/2.0.0/gems/serif-0.5.2/lib/serif/commands.rb:20:in `process'
        from /usr/local/ruby/lib/ruby/gems/2.0.0/gems/serif-0.5.2/bin/serif:7:in `<top (required)>'
        from /usr/local/ruby/bin/serif:23:in `load'
        from /usr/local/ruby/bin/serif:23:in `<main>'
as3:~/serif-site#
```

**Comment by aprescott** [comment]
Closing this since it's an old issue and should be covered in the README.
